services:
  mongodb:
    image: mongo
    container_name: mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME=gufofe}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD=lasexta}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

volumes:
  mongodb_data:

networks:
  mongo_network:
  driver: bridge
