version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gufofe
      MONGO_INITDB_ROOT_PASSWORD: lasexta
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
